# This is a config for E2B sandbox template.
# You can use template ID (7tofcfnuzr8ptzv1shq0) or template name (next-web-ai-builder-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("next-web-ai-builder-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("next-web-ai-builder-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('next-web-ai-builder-3')

team_id = "b179187a-157e-4c68-867b-70186f16992a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "next-web-ai-builder-3"
template_id = "7tofcfnuzr8ptzv1shq0"
